---

  - name: Stage Elasticsearch installation files and processes
    block:

    - name: Get Elasticsearch RPM for Upgrade
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
        dest: /tmp/elasticsearch-{{ elasticsearch_version }}.rpm
        checksum: sha512:https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm.sha512

    - name: Cleanup any lingering transactions that will block next installs
      command: /usr/sbin/yum-complete-transaction --cleanup-only
      changed_when: False

    when:
      - (docker == "server" and inventory_hostname_short | regex_replace('.*[0-9]([0-9])i?$', '\\1') in elasticsearch_data_nodes + elasticsearch_master_nodes) or
        controller == true or
        (quorum == true and datacenter == "core")

